### ISSUE TITLE
MacOS application ?

### ISSUE THREAD

**Issue by cyrilchapon** [ringover/ringover-desktop#1]
There is a link [here](https://www.ringover.com/fr/support/bien-commencer/installer-l-application-ringover-sur-mon-ordinateur) pointing to any unexisting `.dmg` file (404).

When I browse to [releases](https://github.com/ringover/ringover-desktop/releases) in this repo, there isn't any `.dmg`

How to install on MacOS ?

**Comment by JKoehren** [comment]
The MacOS application has been released since March 20, 2020.
